---
title: "MappingCaptureLocations"
author: "HansMartin"
date: "April 2, 2018"
output: html_document
---

Load necessary packages for analysis. (not all of these are actually necessary... )
```{r include=FALSE, echo=FALSE}
#function to install and load required packages
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

#load or install these packages:
packages <- c("ks", "lattice", "plotrix", "adehabitatHR", "maptools", "foreign", "rgdal", "sp", "raster",
              "ggplot2","colorRamps","rgeos","leaflet","lubridate", "htmlwidgets","move", "tmap","grid","dplyr","tidyr")

#run function to install packages
ipak(packages)
```

Load data
```{r}
caploc<-read.csv(file="ImmobilizationDataMarch2018.csv",stringsAsFactors = F)
#format date
#Format the date and time to create a time stamp. 

#loc$LMT24time<-format(strptime(elkdat$LMT_Time,"%I:%M:%S %p"), format="%H:%M:%S") #this function will change 12 hour time to 24 hour time.
  
caploc$LMTmonth<-unlist(lapply(caploc$Date,function(x) strsplit(x, split= "/")[[1]][1])) #extracts month
caploc$LMTday<-unlist(lapply(caploc$Date,function(x) strsplit(x, split= "/")[[1]][2]))#extracts day
caploc$LMTyear<-unlist(lapply(caploc$Date,function(x) strsplit(x, split= "/")[[1]][3]))#extracts year

caploc$LMT24date<-paste(caploc$LMTyear,caploc$LMTmonth,caploc$LMTday, sep="-") #combines date by Year-month-day
#elkdat$timestamp<-paste(elkdat$LMT24date,elkdat$LMT24time,sep=" ") #creates a timestamp
#elkdat$timestamp<-strptime(elkdat$timestamp,format="%Y-%m-%d %H:%M:%S")
#elkdat$LMTtimestamp<-as.POSIXlt(elkdat$timestamp, format="%Y-%m-%d %H:%M:%S",tz="America/Denver") #format the time stamp.
loc<-caploc[caploc$LMTyear>=2018,]
loc<-loc[!is.na(loc$Species),]
```

##Create a spatial points dataframe from capture data

```{r}
  coords<-cbind(loc$Capture.Easting,loc$Capture.Northing) #vector of coordinates
sp=SpatialPoints(coords, #vector of coordinates
                 CRS("+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") #specify the coordinate reference system
                 ) 
locspdf<-SpatialPointsDataFrame(
  coords=sp, 
  data=loc #add data to make this a spatial points data frame
)
```
##Create a spatial points dataframe from survey data

```{r}
surveyloc<-read.csv(file = "ElkAerialSurvey_2018-02-19.csv", stringsAsFactors = F)

coords<-cbind(surveyloc$x_proj,surveyloc$y_proj) #vector of coordinates

sp=SpatialPoints(coords, #vector of coordinates
                 CRS("+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") #specify the coordinate reference system
                 ) 
survlocspdf<-SpatialPointsDataFrame(
  coords=sp, 
  data=surveyloc #add data to make this a spatial points data frameiuvcvbfjlkj
)
```


##Create a spatial points dataframe from survey data

```{r}
summerloc<-read.csv(file = "2017 Summer East Slopes elk survey.csv", stringsAsFactors = F)

coords<-cbind(summerloc$x_proj,summerloc$y_proj) #vector of coordinates

sp=SpatialPoints(coords, #vector of coordinates
                 CRS("+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") #specify the coordinate reference system
                 ) 
sumsurvlocspdf<-SpatialPointsDataFrame(
  coords=sp, 
  data=summerloc #add data to make this a spatial points data frame
)
```
##Load study area extent

```{r}
#Study Extent
studyextent<-readOGR("YHT Study Extent/YHTstudy_extent.shp")
studyextent<-spTransform(studyextent,CRS("+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")) #reproject using the landcover projection
#Ya Ha Tinda Boundary
yahatinda<-readOGR("YaHaTindaShape")
proj4string(yahatinda)<-CRS("+proj=utm +zone=11 +ellps=GRS80 +datum=NAD83 +units=m +no_defs")
yahatinda<-spTransform(yahatinda,CRS("+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))

#Park Regions
BanffRegions<-readOGR("Basebnp_region/basebnp_region.shp")
BanffRegions<-spTransform(BanffRegions,CRS("+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))

#Elevation Raster
#elevation<-raster("elevationDEMYHTBANFF.tif")

```

##Creating a camera locations figure in tmap
```{r, fig.height=10, fig.width=12}

locmap<-
  #specifies how r should plot the file (either as a raster, polygon, line, symbol)
  #tm_shape(BanffRegions)+ # loads banff shape file
  #tm_polygons(alpha = .5)+ #plots the shapefile as a polygonalpha =0.5 controls transparency (0-1)
tm_shape(studyextent, is.master=T)+# loads banff shape file
 tm_borders(col = "Red")+ #plots only the boundary of the shapefile 
# tm_shape(elevation)+ #loads file (either shape file, raster file, etc...)
#   tm_raster()+
  
tm_shape(survlocspdf,
           is.master = F)+
 tm_bubbles(size="Total",
              col="Sex",
            shape=1,
            size.lim = c(1,300),
              title.size="Group Size",
              title.col = "Winter Aerial Survey Locations Group Composition")+
tm_shape(sumsurvlocspdf,
           is.master = F)+
 tm_bubbles(size="Total",
              col="Sex",
            shape=2,
            size.lim = c(1,300),
              title.size="Group Size",
              title.col = "Summer Aerial Survey Location Group Composition",
              title.shape = "")+
  
tm_shape(yahatinda)+
  tm_borders(col="black")+

tm_shape(locspdf)+
  tm_symbols(size=0.07, #plots the spatialpoints dataframe as symbols
             shape=3,
             col="Sex", #color is associated with the column "park" in the spatialpointsdataframe
             title.col =  "Capture Location and Sex"
             )+
  tm_style_col_blind()+ #uses a colorblind cooperative colorscheme for the symbols
  

  
  tm_compass(position=c("right", "top"))+ #inserts a compass showing north.
  
  tm_add_legend(type="line", col=c("red"), title="Study Area") + #adds a custom legend
  
  #tm_add_legend(type="fill", col=c("lightgrey"), title="National Park Boundary") + #adds a custom legend 
  
  #tm_add_legend(type="fill", col=c("darkgray"), title="Ya Ha Tinda Ranch") +#adds a custom legend
  
  
    
  tm_layout(
    main.title = "Capture and Summer and Winter Aerial Survey Locations of Elk",#text for main title
            main.title.size = 2, #size of main title
            main.title.position= c("center"),#position of main title ("top","right","bottom")
            #outer.margins = c(0,0,0,0.01), 
            #inner.margins = c(0.01,0.01,0.01,0.11), 
            #between.margin = 0.1,
            compass.type = "arrow", #type of compass rose
            legend.outside = T, # places the legend inside the map or outside
            legend.title.size=0.75,
            legend.text.size=0.5,
            legend.just = c("right", "top")#specifies legend location
    ) 
locmap
# #create an inset map
# yahatindamap<-tm_shape(yahatinda)+ #spatial data to use
#   tm_polygons(col="darkgrey")+
#   tm_shape(yhtcamlocspdf)+
#     tm_symbols(col="darkgreen", size=0.15)+
#   tm_layout(main.title = "Ya Ha Tinda Ranch",
#             main.title.size = 0.6, 
#             main.title.position= c("center"))

save_tmap(tm=locmap, #object name
          filename="SurveyAndCaptureLocations.tiff", #save map to this filename
          width=5, #width of saved image
          height=4, #height of saved image
          units="in", #units "in", "cm"
          dpi=600#, #dpi
          #insets_tm = yahatindamap, #tmap object to inset
          #insets_vp=viewport(x=0.2, y=0.155, width=0.4, height=0.4) #location of the inset map
          )

```